'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class libros
    Public Property codigo As Integer
    Public Property signatura As String
    Public Property titulo As String
    Public Property autor As String
    Public Property disponible As String

End Class
Partial Public Class prestamos
    Public Property id As Integer
    Public Property nif As String
    Public Property codigo As Integer
    Public Property prestamo As Date

End Class
Partial Public Class socios
    Public Property nif As String
    Public Property nombre As String
    Public Property apellidos As String
    Public Property direccion As String
    Public Property cp As String
    Public Property alta As Date

End Class
