'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations

Partial Public Class libros
    <Required()>
    Public Property codigo As Integer

    <Required(ErrorMessage:="El libro debe contar con una signatura"),
     StringLength(10, MinimumLength:=3, ErrorMessage:="La signatura debe tener entre 3 y 10 caracteres")>
    Public Property signatura As String

    Public Property titulo As String

    Public Property autor As String

    Public Property disponible As String

End Class
