'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class socios
    Public Property nif As String
    Public Property nombre As String
    Public Property apellidos As String
    Public Property direccion As String
    Public Property cp As String
    Public Property alta As Date

End Class
